# Generated by Django 4.2.6 on 2026-05-05 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.AlterModelOptions(
            name='aboutme',
            options={'verbose_name': 'About Me', 'verbose_name_plural': 'About Me'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at']},
        ),
    ]
